### PR TITLE
Created 2 reusable components, minor css fixes and fixed eslint warnings

### PR DESCRIPTION
**Pull request by gervjo**
- Modified the `viewport` meta tag for better responsive viewport control.
- Created a reusable component `ResetGridButton` that is used in the different views to "reset" the data tree state of the sync grid.
- Created a reusable component `SelectPokemonDropdown` that is used on all views to "select" a pokemon's sync grid.
- Minor CSS fixes for layout and viewport "responsiveness".
- Added `redux-devtools-extension` as a dev-dependency for better easier dev and debug of `redux` actions and data tree.
- Fixed a couple of `eslint` warnings.

### CODE REVIEW

**Comment by pokemon-masters-stuff** [comment]
Thanks so much gervjo! I think these changes look great. There is one thing though - when I changed the screen size to Mobile L - 425px, the ActiveGridList component covers a big portion of the GridData component to the extent that the user wouldn't be able to see the energy cost. I attached a screenshot. Also, do you mind if we keep the width of the ActiveGridList the same as the GridData so that they look nice together on mobile phones?

Capture

**Comment by gervjo** [comment]
Yes sure not a problem. Sorry for that, I did not noticed that they were overlapping each other.
I will revert the CSS changes which affect the `active-grid-list` class name.

**Comment by gervjo** [comment]
@pokemon-masters-stuff changes have been reverted.

**Comment by pokemon-masters-stuff** [comment]
Looks great now. Thank you so much! I just merged it. Also added color to Serperior's grids.

**Pull request merged**
